import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { Miniflare, convertV4MiniflareOptions } from 'miniflare';
test('Carteiras isoladas, contatos, concorrência e histórico atômico',async()=>{
  const mf=new Miniflare(convertV4MiniflareOptions({modules:[{type:'ESModule',path:'src/worker/index.js'},{type:'ESModule',path:'src/domain/password.js'},{type:'ESModule',path:'src/worker/leads.js'},{type:'ESModule',path:'src/domain/leads.js'}, { type: 'ESModule', path: 'src/domain/duplicates.js' }, { type: 'ESModule', path: 'src/worker/duplicates.js' }, { type: 'ESModule', path: 'src/domain/whatsapp.js' }, { type: 'ESModule', path: 'src/domain/contact-outcomes.js' }, { type: 'ESModule', path: 'src/worker/reports.js' }, {type:'ESModule',path:'src/worker/companies.js'}],modulesRoot:'src',compatibilityDate:'2026-09-25',compatibilityFlags:['nodejs_compat'],d1Databases:['DB']}));
  try {
    const db=await mf.getD1Database('DB');
    for(const file of ['0001_auth.sql','0002_captacoes.sql','0003_duplicates.sql','0004_contact_outcomes.sql','0005_proprietor.sql','0006_user_management.sql','0007_companies.sql']) {
      const sql=await readFile(`migrations/${file}`,'utf8');
      // D1 exec accepts multi-statement SQL when each complete statement is on one line.
      const statements=sql.trim().split(/(?<=;)\s*(?=CREATE|PRAGMA|ALTER|DROP|UPDATE|DELETE)/);
      for(const statement of statements) await db.prepare(statement.trim()).run();
    }
    await db.prepare("INSERT INTO companies (id,slug,name,created_at) VALUES ('fixture','fixture','Criativa Imóveis',0)").run();
    const tokens={};
    for(const [id,role] of [['a','CAPTADOR'],['b','CAPTADOR'],['admin','ADMIN']]) {
      tokens[id]=(id==='a'?'a':id==='b'?'b':'c').repeat(64);
      const hash=Buffer.from(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(tokens[id]))).toString('hex');
      await db.prepare(`INSERT INTO users (id,name,email,password_hash,role,active,created_at,company_id,access_role) VALUES (?,?,?,?,?,1,?,'fixture',?)`).bind(id,id,`${id}@example.test`,'unused',role,Date.now(),role==='ADMIN'?'BROKER':'CAPTADOR').run();
      await db.prepare('INSERT INTO sessions VALUES (?,?,?)').bind(hash,id,Date.now()+600000).run();
    }
    const req=(as,path,method='GET',body)=>mf.dispatchFetch(`https://test.local/api/${path}`,{method,headers:{Origin:'https://test.local','Content-Type':'application/json',Cookie:`captabit_session=${tokens[as]}`},...(body?{body:JSON.stringify(body)}:{})});
    const input={proprietor_name:'Maria Proprietária',type:'Casa',purpose:'Locação',street:'Rua de teste',city:'Teste',phones:['51999991111','51999992222']};
    assert.equal((await req('a','leads','POST',{...input,proprietor_name:''})).status,400);
    assert.equal((await req('a','leads','POST',{...input,proprietor_name:'   '})).status,400);
    const response=await req('a','leads','POST',input); assert.equal(response.status,201,await response.clone().text());
    const {lead}=await response.json(); const id=lead.id;
    assert.equal(lead.owner_id,'a');
    assert.equal((await req('a','leads','POST',{...input,owner_id:'b'})).status,400);
    assert.equal((await req('b',`leads/${id}`)).status,404);
    assert.equal((await req('b',`leads/${id}/history`)).status,404);
    assert.equal((await req('b',`leads/${id}/contacts`,'POST',{phone:'51999993333'})).status,404);
    assert.equal((await (await req('b','leads?q=Rua')).json()).leads.length,0);
    assert.equal((await (await req('a','leads?q=Rua')).json()).leads.length,1);
    assert.equal((await (await req('admin','leads')).json()).leads.length,1);
    const {contacts}=await (await req('a',`leads/${id}`)).json(); assert.equal(contacts.length,2);
    assert.equal((await req('b',`leads/${id}/contacts/${contacts[0].id}`,'PATCH',{status:'Mensagem enviada',version:1})).status,404);
    assert.equal((await req('a',`leads/${id}/contacts/${contacts[0].id}`,'PATCH',{status:'Mensagem enviada',version:1})).status,200);
    assert.equal((await req('a',`leads/${id}/contacts/${contacts[0].id}`,'PATCH',{status:'Sem resposta',version:1})).status,409);
    assert.equal((await req('a',`leads/${id}/contacts`,'POST',{phone:contacts[0].phone})).status,409);
    const concurrent=await Promise.all([req('a',`leads/${id}`,'PATCH',{status:'Em pesquisa',version:1}),req('a',`leads/${id}`,'PATCH',{status:'Em contato',version:1})]);
    assert.deepEqual(concurrent.map(r=>r.status).sort(),[200,409]);
    const history=await (await req('a',`leads/${id}/history`)).json(); assert.equal(history.events.length,5);
    assert.equal((await req('a',`leads/${id}`,'PATCH',{owner_id:'b',version:2})).status,403);
    assert.equal((await req('admin',`leads/${id}`,'PATCH',{owner_id:'b',version:2})).status,200);
    assert.equal((await req('a',`leads/${id}`)).status,404);
    assert.equal((await req('a',`leads/${id}/contacts/${contacts[0].id}`,'PATCH',{status:'Sem resposta',version:2})).status,404);
    assert.equal((await req('b',`leads/${id}`)).status,200);
    assert.equal((await req('b',`leads/${id}`,'PATCH',{status:'Captado',version:3})).status,200);
    assert.equal((await req('b',`leads/${id}`,'PATCH',{status:'Nova',version:4})).status,403);
    assert.equal((await req('admin',`leads/${id}`,'PATCH',{status:'Nova',version:4})).status,200);
    const count=await db.prepare('SELECT COUNT(*) AS n FROM leads').first();
    assert.equal((await req('a','leads','POST',{...input,phones:['inválido']})).status,400);
    assert.deepEqual(await db.prepare('SELECT COUNT(*) AS n FROM leads').first(),count);
    assert.equal((await req('a','leads?page=-1')).status,400);
    const privateInput={...input,street:'Av. São João',city:'Porto Alegre',state:'RS',number:'0123',complement:'Apto 101',notes:'SEGREDO-NAO-EXIBIR',phones:['51999994444']};
    const privateResult=await (await req('b','leads','POST',privateInput)).json();
    const checkInput={...privateInput,street:'Avenida Sao Joao',number:'123',complement:'Apartamento 101'};
    const check=await (await req('a','leads/duplicates','POST',checkInput)).json();
    assert.ok(check.duplicates.items.some(item=>item.type==='Endereço correspondente'));
    assert.ok(check.duplicates.items.some(item=>item.type==='Telefone já cadastrado'));
    assert.doesNotMatch(JSON.stringify(check),/SEGREDO|51999994444|street|phone|owner_id/);
    assert.ok(!JSON.stringify(check).includes(privateResult.lead.id));
    const otherApartment=await (await req('a','leads/duplicates','POST',{...checkInput,complement:'Apto 102',phones:[]})).json();
    assert.equal(otherApartment.duplicates.items.length,0);
    const incomplete=await (await req('a','leads/duplicates','POST',{...checkInput,number:'',complement:'',phones:[]})).json();
    assert.equal(incomplete.duplicates.incomplete,true);
    assert.ok(incomplete.duplicates.items.length>0);
    assert.equal((await req('a',`leads/${privateResult.lead.id}/whatsapp/fake`,'POST',{message:'Olá',version:1})).status,404);
    const own=await (await req('b',`leads/${privateResult.lead.id}`)).json();
    const recipient=own.contacts[0];
    const eventsBefore=(await (await req('b',`leads/${privateResult.lead.id}/history`)).json()).events.length;
    const wa=await (await req('b',`leads/${privateResult.lead.id}/whatsapp/${recipient.id}`,'POST',{message:'Olá & tudo bem?',version:recipient.version,acknowledge:true})).json();
    assert.equal(new URL(wa.url).hostname,'wa.me');assert.match(new URL(wa.url).searchParams.get('text'),/Sou b, corretor de locações da Criativa Imóveis/);
    const after=(await (await req('b',`leads/${privateResult.lead.id}`)).json()).contacts[0];
    assert.equal(after.status,'Não contatado');assert.equal(after.version,recipient.version);
    assert.equal((await (await req('b',`leads/${privateResult.lead.id}/history`)).json()).events.length,eventsBefore+1);
    await req('b',`leads/${privateResult.lead.id}`,'PATCH',{status:'Recusado',version:1});
    const historical=await (await req('a','leads/duplicates','POST',checkInput)).json();
    assert.ok(historical.duplicates.items.every(item=>item.historical));
    const historyBeforeIndex=await db.prepare('SELECT COUNT(*) AS n FROM lead_events').first();
    await db.prepare('UPDATE leads SET key_version=1 WHERE id=?').bind(id).run();
    assert.deepEqual(await db.prepare('SELECT COUNT(*) AS n FROM lead_events').first(),historyBeforeIndex);
    const changed=await req('admin',`leads/${privateResult.lead.id}`,'PATCH',{street:'Rua Diferente',version:2});
    assert.equal(changed.status,200);
    const noOldAddress=await (await req('a','leads/duplicates','POST',{...checkInput,phones:[]})).json();
    assert.equal(noOldAddress.duplicates.items.length,0);
    const route=`leads/${privateResult.lead.id}/contacts/${recipient.id}`;
    assert.equal((await req('a',route,'DELETE',{version:1})).status,404);
    assert.equal((await req('b',route,'PATCH',{outcome:'INVALID',version:1})).status,400);
    let version=1;
    for(const outcome of ['CORRECT','INCORRECT','NO_RESPONSE','NO_WHATSAPP']) {
      assert.equal((await req('b',route,'PATCH',{outcome,version})).status,200);version++;
      const detail=await (await req('b',`leads/${privateResult.lead.id}`)).json();
      assert.equal(detail.contacts[0].outcome,outcome);
      assert.equal(detail.lead.status,'Recusado');
      if(['INCORRECT','NO_WHATSAPP'].includes(outcome)) assert.equal((await req('b',`leads/${privateResult.lead.id}/whatsapp/${recipient.id}`,'POST',{version})).status,409);
    }
    assert.equal((await req('b',route,'DELETE',{version:1})).status,409);
    assert.equal((await req('b',route,'DELETE',{version})).status,200);
    assert.equal((await (await req('b',`leads/${privateResult.lead.id}`)).json()).contacts.length,0);
    assert.equal((await (await req('b','leads?q=51999994444')).json()).leads.length,0);
    assert.equal((await (await req('a','leads/duplicates','POST',checkInput)).json()).duplicates.items.length,0);
    assert.equal((await req('b',route,'PATCH',{outcome:'CORRECT',version:version+1})).status,404);
    assert.equal((await req('b',`leads/${privateResult.lead.id}/whatsapp/${recipient.id}`,'POST',{version:version+1})).status,404);
    assert.ok((await (await req('b',`leads/${privateResult.lead.id}/history`)).json()).events.some(e=>e.event==='Contato excluído'));
    const restored=await req('b',`leads/${privateResult.lead.id}/contacts`,'POST',{phone:recipient.phone});
    assert.equal(restored.status,201);assert.equal((await restored.json()).id,recipient.id);
    const restoredContact=(await (await req('b',`leads/${privateResult.lead.id}`)).json()).contacts[0];
    assert.equal(restoredContact.outcome,'UNKNOWN');assert.equal(restoredContact.version,version+2);
    const another=await req('b','leads','POST',{...input,phones:[]});
    assert.equal(another.status,201);
    const anotherLead=(await another.json()).lead;
    assert.equal((await req('b',`leads/${anotherLead.id}`,'PATCH',{proprietor_name:'Maria Atualizada',version:1})).status,200);
    const found=await (await req('b','leads?q=Maria%20Atualizada')).json();assert.equal(found.leads.length,1);
    assert.equal((await (await req('a','leads?q=Maria%20Atualizada')).json()).leads.length,0);
    const ownerHistory=await (await req('b',`leads/${anotherLead.id}/history`)).json();
    assert.equal(ownerHistory.events[0].after.proprietor_name,'Maria Atualizada');
    assert.equal(ownerHistory.events[0].before.proprietor_name,'Maria Proprietária');
    const waPath=`leads/${privateResult.lead.id}/whatsapp/${recipient.id}`;
    const currentVersion=restoredContact.version;
    assert.equal((await req('b',waPath,'POST',{version:currentVersion,templateId:'invalid'})).status,400);
    assert.equal((await req('b',waPath,'POST',{version:currentVersion,templateId:'confirmed'})).status,400);
    for(const templateId of ['initial','direct','friendly']) {
      const response=await req('b',waPath,'POST',{version:currentVersion,templateId,acknowledge:true});
      assert.equal(response.status,200);assert.equal(new URL((await response.json()).url).hostname,'wa.me');
    }
    assert.equal((await req('b',route,'PATCH',{version:currentVersion,outcome:'CORRECT'})).status,200);
    assert.equal((await req('b',waPath,'POST',{version:currentVersion+1,templateId:'confirmed',acknowledge:true})).status,200);
    const latest=(await (await req('b',`leads/${privateResult.lead.id}/history`)).json()).events[0];
    assert.equal(latest.after.message_model,'Captação certeira');
    const unchanged=(await (await req('b',`leads/${privateResult.lead.id}`)).json()).contacts[0];
    assert.equal(unchanged.status,'Não contatado');assert.equal(unchanged.version,currentVersion+1);
    const preservedHistory=(await (await req('admin',`leads/${privateResult.lead.id}/history`)).json()).events;
    assert.equal((await req('admin','users/b','DELETE')).status,200);
    assert.equal((await req('b',`leads/${privateResult.lead.id}`)).status,401);
    const preserved=await (await req('admin',`leads/${privateResult.lead.id}`)).json();
    assert.equal(preserved.lead.owner_id,'b');assert.equal(preserved.contacts.length,1);
    assert.deepEqual((await (await req('admin',`leads/${privateResult.lead.id}/history`)).json()).events,preservedHistory);
    assert.ok((await (await req('admin','reports/captacoes?owner_id=b')).json()).total>0);
  } finally {await mf.dispose();}
});
